import { Product, SubscriptionPlan, Order, TrackingStep, Feedback, BusinessInfo } from "@/types";

// Premium Organic Meat Products
export const PRODUCTS: Product[] = [
  // Chicken Category
  {
    id: 1,
    name: "Organic Chicken Breast",
    category: "chicken",
    description: "Antibiotic-free chicken breast from certified organic farms. Perfect for grilling, baking, or pan-searing. High in protein, low in fat.",
    price: 450,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Organic", "Free-range"],
    farmOrigin: "Green Valley Farm, Coimbatore",
    freshness: "Fresh from farm - 24hrs",
    tag: "Premium",
    badge: "Best Seller",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&q=80",
    stock: 50,
    qrCode: "QR001",
    nutrients: { protein: "31g", fat: "3.6g", calories: "165" },
  },
  {
    id: 2,
    name: "Grass-fed Whole Chicken",
    category: "chicken",
    description: "Whole chicken raised on grass pasture with no antibiotics. Superior taste and higher omega-3 content. Perfect for family meals.",
    price: 599,
    unit: "per 1.5kg",
    weight: "1.5kg",
    certifications: ["Organic", "Grass-fed"],
    farmOrigin: "Nilgiri Organic Co-op",
    freshness: "Fresh - 24hrs",
    tag: "Premium",
    badge: "Popular",
    emoji: "🐔",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&q=80",
    stock: 30,
    qrCode: "QR002",
  },
  {
    id: 3,
    name: "Organic Chicken Thighs",
    category: "chicken",
    description: "Tender, juicy chicken thighs perfect for curries and stews. More flavorful than breast meat with higher nutrient density.",
    price: 350,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Organic"],
    farmOrigin: "Salem Organic Farm",
    freshness: "Fresh - 24hrs",
    tag: "Regular",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&q=80",
    stock: 45,
    qrCode: "QR003",
  },

  // Mutton/Lamb Category
  {
    id: 4,
    name: "Organic Mutton Curry Cut",
    category: "mutton",
    description: "Fresh mutton pieces cut perfectly for curries. Sourced from free-range farms. Rich, authentic taste perfect for traditional recipes.",
    price: 650,
    unit: "per 750g",
    weight: "750g",
    certifications: ["Organic", "Free-range"],
    farmOrigin: "Ooty Highland Farms",
    freshness: "Fresh - 12hrs",
    tag: "Premium",
    badge: "New",
    emoji: "🐑",
    image: "https://images.unsplash.com/photo-1599505782212-f1bf61b0e01e?w=600&q=80",
    stock: 25,
    qrCode: "QR004",
  },
  {
    id: 5,
    name: "Grass-fed Lamb Chops",
    category: "mutton",
    description: "Premium lamb chops from grass-fed sheep. Lean, tender, and flavorful. Ideal for grilling or pan-searing with minimal seasoning.",
    price: 750,
    unit: "per 600g",
    weight: "600g",
    certifications: ["Organic", "Grass-fed"],
    farmOrigin: "Kodaikanal Organic Ranch",
    freshness: "Fresh - 12hrs",
    tag: "Premium",
    badge: "Seasonal",
    emoji: "💚",
    image: "https://images.unsplash.com/photo-1599505782212-f1bf61b0e01e?w=600&q=80",
    stock: 20,
    qrCode: "QR005",
  },
  {
    id: 6,
    name: "Organic Goat Meat",
    category: "mutton",
    description: "Lean and highly nutritious goat meat from certified farms. Traditional choice in South Indian cuisine. Very low in fat.",
    price: 580,
    unit: "per 600g",
    weight: "600g",
    certifications: ["Organic"],
    farmOrigin: "Dindigul Organic Cooperative",
    freshness: "Fresh - 12hrs",
    tag: "Special",
    emoji: "🐐",
    image: "https://images.unsplash.com/photo-1599505782212-f1bf61b0e01e?w=600&q=80",
    stock: 18,
    qrCode: "QR006",
  },

  // Fish & Seafood Category
  {
    id: 7,
    name: "Fresh Tilapia Fillet",
    category: "fish",
    description: "Delicate white fish fillet. Mercury-free, sustainably sourced from certified farms. Perfect for healthy, light meals.",
    price: 420,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Organic", "Sustainable"],
    farmOrigin: "Backwater Farms, Kerala",
    freshness: "Fresh - 6hrs",
    tag: "Regular",
    badge: "Popular",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1580959375944-abd7e991e971?w=600&q=80",
    stock: 35,
    qrCode: "QR007",
  },
  {
    id: 8,
    name: "Wild-Caught Mackerel",
    category: "fish",
    description: "Rich in Omega-3 fatty acids. Wild-caught from sustainable fisheries. Strong, authentic fish flavor perfect for traditional recipes.",
    price: 520,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Sustainable", "Wild-caught"],
    farmOrigin: "Arabian Sea, Maharashtra",
    freshness: "Fresh - 4hrs",
    tag: "Premium",
    badge: "Best Seller",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1580959375944-abd7e991e971?w=600&q=80",
    stock: 28,
    qrCode: "QR008",
  },
  {
    id: 9,
    name: "Fresh Pomfret",
    category: "fish",
    description: "Whole pomfret fish with delicate, mild taste. Perfect for grilling or steaming. Best quality available in the market.",
    price: 480,
    unit: "per 400g",
    weight: "400g",
    certifications: ["Sustainable"],
    farmOrigin: "Tamil Nadu Coast",
    freshness: "Fresh - 6hrs",
    tag: "Premium",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1580959375944-abd7e991e971?w=600&q=80",
    stock: 22,
    qrCode: "QR009",
  },

  // Specialties Category
  {
    id: 10,
    name: "Biodynamic Beef",
    category: "specialties",
    description: "Extremely limited stock. Rare premium beef from biodynamic farm with superior fat distribution and taste. Ultra high-quality.",
    price: 890,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Biodynamic", "Grass-fed"],
    farmOrigin: "Mysore Biodynamic Farm",
    freshness: "Fresh - 24hrs",
    tag: "Ultra-Premium",
    badge: "Seasonal",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1588167056534-39c7005e4330?w=600&q=80",
    stock: 8,
    qrCode: "QR010",
  },
  {
    id: 11,
    name: "Organic Rabbit Meat",
    category: "specialties",
    description: "Lean, tender rabbit meat very rich in protein and low in fat. Very nutritious. Sourced from certified organic farms.",
    price: 680,
    unit: "per 500g",
    weight: "500g",
    certifications: ["Organic"],
    farmOrigin: "Nilgiri Organic Co-op",
    freshness: "Fresh - 12hrs",
    tag: "Special",
    badge: "New",
    emoji: "🐰",
    image: "https://images.unsplash.com/photo-1588167056534-39c7005e4330?w=600&q=80",
    stock: 12,
    qrCode: "QR011",
  },
  {
    id: 12,
    name: "Duck Breast Premium Cut",
    category: "specialties",
    description: "Premium duck breast with skin on. Rich flavor, perfect for pan-searing. Free-range sourced from certified farms.",
    price: 520,
    unit: "per 400g",
    weight: "400g",
    certifications: ["Organic", "Free-range"],
    farmOrigin: "Kannur Organic Farm",
    freshness: "Fresh - 24hrs",
    tag: "Premium",
    emoji: "🦆",
    image: "https://images.unsplash.com/photo-1588167056534-39c7005e4330?w=600&q=80",
    stock: 15,
    qrCode: "QR012",
  },
];

// Subscription Plans
export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 1,
    name: "Starter Cut",
    frequency: "weekly",
    basePrice: 999,
    discountPercentage: 5,
    description: "Perfect for families just starting their organic journey",
    benefits: [
      "Organic certification verified",
      "Free cold-chain delivery",
      "7-day freshness guarantee",
      "Flexible pause/skip",
    ],
    items: [
      { productId: 1, quantity: 1, optional: false },
      { productId: 7, quantity: 1, optional: true },
    ],
  },
  {
    id: 2,
    name: "Premium Box",
    frequency: "weekly",
    basePrice: 1799,
    discountPercentage: 12,
    description: "Premium cuts from finest farms - variety included",
    benefits: [
      "All Starter benefits",
      "Premium cuts included",
      "15% discount on add-ons",
      "Priority delivery slot",
    ],
    items: [
      { productId: 1, quantity: 2, optional: false },
      { productId: 4, quantity: 1, optional: true },
      { productId: 8, quantity: 1, optional: true },
    ],
    popularBadge: true,
  },
  {
    id: 3,
    name: "Biodynamic Deluxe",
    frequency: "biweekly",
    basePrice: 3499,
    discountPercentage: 18,
    description: "Maximum variety with premium & specialty cuts",
    benefits: [
      "All Premium benefits",
      "Specialty cuts access",
      "20% discount on everything",
      "Dedicated customer support",
    ],
    items: [
      { productId: 1, quantity: 2, optional: false },
      { productId: 4, quantity: 1, optional: false },
      { productId: 10, quantity: 1, optional: true },
    ],
  },
];

// Tracking Steps
export const TRACKING_STEPS: TrackingStep[] = [
  {
    key: "confirmed",
    label: "Order Confirmed",
    description: "Your order has been received and verified",
    icon: "✓",
  },
  {
    key: "preparing",
    label: "Being Packaged",
    description: "Your meat is being carefully packaged",
    icon: "📦",
  },
  {
    key: "quality_check",
    label: "Quality Check",
    description: "Freshness verified & cold-chain ready",
    icon: "❄️",
  },
  {
    key: "out_for_delivery",
    label: "Out for Delivery",
    description: "Your order is on its way in refrigerated vehicle",
    icon: "🚚",
  },
  {
    key: "delivered",
    label: "Delivered",
    description: "Enjoy your fresh organic meat!",
    icon: "🏠",
  },
];

// Sample Demo Orders
export const DEMO_ORDERS: Order[] = [
  {
    id: "OMO-001",
    userId: "user1",
    customerName: "Rajesh Kumar",
    email: "rajesh@email.com",
    phone: "+91 98765 43210",
    address: "123 Anna Salai",
    city: "Chennai",
    pincode: "600002",
    deliveryTime: "Morning (6am–9am)",
    notes: "Please ring bell twice",
    items: [
      {
        ...PRODUCTS[0],
        quantity: 2,
      },
      {
        ...PRODUCTS[7],
        quantity: 1,
      },
    ],
    total: 1420,
    status: "out_for_delivery",
    createdAt: "2024-01-15T05:00:00Z",
    updatedAt: "2024-01-15T09:14:00Z",
    driver: "Marcus R.",
    eta: 15,
    latitude: 13.0827,
    longitude: 80.2707,
    deliveryType: "sameDay",
    paymentMethod: "upi",
    paymentStatus: "completed",
  },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Devipriyanka",
    city: "Coimbatore",
    rating: 5,
    comment: "Finally found a reliable source for organic meat in Coimbatore! The quality is exceptional and delivery is always on time. The QR code traceability gives me complete peace of mind about the farm origin.",
    image: "👩",
  },
  {
    id: 2,
    name: "Amit Patel",
    city: "Coimbatore",
    rating: 5,
    comment: "Been subscribing for 3 months now. The subscription model saves me money and ensures I always have fresh organic meat. Customer service is excellent!",
    image: "👨",
  },
  {
    id: 3,
    name: "Kerala Housewife",
    city: "Kochin",
    rating: 5,
    comment: "The pomfret and mackerel are the freshest I've bought. Worth every rupee. Highly recommend for health-conscious families.",
    image: "👩‍🍳",
  },
];

// Business Information
export const BUSINESS_INFO: BusinessInfo = {
  name: "OrganiMeat",
  description: "Premium organic, grass-fed, and free-range meat from certified farms",
  registrationNumber: "TN/BUS/2023/001234",
  fssaiLicense: "10013045001478",
  fssaiExpiry: "2025-12-31",
  certifications: [
    {
      title: "FSSAI License",
      issuer: "Food Safety and Standards Authority of India",
      expiryDate: "2025-12-31",
      certificateUrl: "/cert-fssai.pdf",
    },
  ],
  farms: [
    {
      name: "Green Valley Farm",
      location: "Coimbatore, Tamil Nadu",
      certifications: ["Organic", "Free-range"],
      description: "Major supplier of organic chicken. Uses traditional farming methods with zero antibiotics.",
    },
    {
      name: "Nilgiri Organic Co-op",
      location: "Nilgiri, Tamil Nadu",
      certifications: ["Organic", "Grass-fed"],
      description: "Cooperative of small farmers producing organic mutton and goat meat.",
    },
  ],
  policies: [
    {
      title: "Freshness Guarantee",
      content: "All meat is delivered within 24 hours of processing. If not satisfied, we offer full refund.",
    },
  ],
};
